---
- name: do not match administrators group
  community.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regex: "^#?Match Group administrators"
    line: "#Match Group administrators"
  notify: restart sshd

- name: do not set authorized_keys file for administrators
  community.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regex: "^#?\\s+AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys"
    line: "#        AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys"
  notify: restart sshd
